name: cmake-git-hash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Do not stop all jobs if a single job fails.
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, Windows-2019, macos-11]
        # os: [macos-latest]
        os: [ubuntu-20.04]
        build-type: ['Debug', 'Release']

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Create build folder
        run: |
          mkdir ${{ github.workspace }}/example/build

      - name: Run CMake
        working-directory: ${{ github.workspace }}/example/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        working-directory: ${{ github.workspace }}/example/build
        run: |
          cmake --build . --config ${{ matrix.build-type }} --verbose

      - name: Run test
        working-directory: ${{ github.workspace }}/example/build
        run: |
          ctest -C ${{ matrix.build-type }} -V
